name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      strategy:
        matrix:
          goos: [linux]
          goarch: [amd64]
        fail-fast: false
      
      runs-on: ubuntu-latest
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
        CGO_ENABLED: 0
      steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Main
        run: go build -o goseeder main.go

      - name: Build Stat Tool
        run: go build -o gostat stat.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: my-artifact
          path: |
            goseeder
            gostat


